package constanta

const (
	BLOOD_TYPE_A_POSITIVE		= "A+"
	BLOOD_TYPE_A_NEGATIVE		= "A-"
	BLOOD_TYPE_A_UNKNOWN		= "A"

	BLOOD_TYPE_B_POSITIVE		= "B+"
	BLOOD_TYPE_B_NEGATIVE		= "B-"
	BLOOD_TYPE_B_UNKNOWN		= "B"

	BLOOD_TYPE_AB_POSITIVE		= "AB+"
	BLOOD_TYPE_AB_NEGATIVE		= "AB-"
	BLOOD_TYPE_AB_UNKNOWN		= "AB"

	BLOOD_TYPE_O_POSITIVE		= "O+"
	BLOOD_TYPE_O_NEGATIVE		= "O-"
	BLOOD_TYPE_O_UNKNOWN		= "O"
)

var BloodList = []string {
	BLOOD_TYPE_A_POSITIVE,
	BLOOD_TYPE_A_NEGATIVE,
	BLOOD_TYPE_A_UNKNOWN,
	BLOOD_TYPE_B_POSITIVE,
	BLOOD_TYPE_B_NEGATIVE,
	BLOOD_TYPE_B_UNKNOWN,
	BLOOD_TYPE_AB_POSITIVE,
	BLOOD_TYPE_AB_NEGATIVE,
	BLOOD_TYPE_AB_UNKNOWN,
	BLOOD_TYPE_O_POSITIVE,
	BLOOD_TYPE_O_NEGATIVE,
	BLOOD_TYPE_O_UNKNOWN,
}